"""
Django settings for vehicleRentalSystem project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

"""
Django settings for vehicleRentalSystem project.
Gộp cấu trúc Apps của Bảo/Hiếu và Logic Static của Frontend.
"""

import os
from pathlib import Path

# 1. Định nghĩa thư mục gốc
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Cấu hình Bảo mật (Chỉ dùng DEBUG=True khi phát triển)
SECRET_KEY = 'django-insecure-^u30-jmlkmxhizxcva5*vy56kj)3beu^n%e%u!z8yfr60tv*ae'
DEBUG = True
ALLOWED_HOSTS = []

# 3. Đăng ký các ứng dụng (Apps)
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Nhóm Apps chức năng (Bảo & Hiếu)
    'users',      # Quản lý người dùng & Custom User Model
    'bookings',   # Quản lý đặt xe & Thanh toán
    'vehicles',   # Quản lý phương tiện & Maps
    
    # Nhóm App giao diện (Frontend/Sass)
    'frontend',   
]

# 4. Custom User Model (Yêu cầu bắt buộc từ App users)
AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vehicleRentalSystem.urls'

# 5. Cấu hình Templates (Trỏ về thư mục chứa base.html của bạn)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'], # Ưu tiên templates từ frontend app
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vehicleRentalSystem.wsgi.application'

# 6. Database (PostgreSQL - Chạy qua Docker theo thiết kế của nhóm)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'vehicle_rental_system',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'db', # Tên service db trong docker-compose
        'PORT': 5432,
    }
}

# 7. Ngôn ngữ và Thời gian (Việt Nam)
LANGUAGE_CODE = 'vi'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = True

# 8. Cấu hình Static Files (CSS/Sass biên dịch thủ công)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "static", # Nơi chứa frontend/static/frontend/scss/main.css
]
# STATIC_ROOT dùng khi triển khai thực tế (collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"

# 9. Cấu hình Media (Ảnh xe, GPLX)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'