# Generated by Django 5.1.4 on 2026-01-27 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên xe')),
                ('price_per_day', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá thuê/ngày')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Ảnh xe')),
                ('is_available', models.BooleanField(default=True, verbose_name='Sẵn sàng')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Sao - Tệ'), (2, '2 Sao - Kém'), (3, '3 Sao - Bình thường'), (4, '4 Sao - Tốt'), (5, '5 Sao - Tuyệt vời')], default=5, verbose_name='Điểm đánh giá')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vehicles.vehicle', verbose_name='Xe')),
            ],
        ),
    ]
