# Generated by Django 5.1.4 on 2026-01-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_image_vehicle_latitude_vehicle_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner',
            new_name='customer',
        ),
    ]
