# Generated by Django 5.1.4 on 2026-01-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_rename_owner_vehicle_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='customer',
        ),
    ]
